name: ${plugin.name}
main: com.vexsoftware.votifier.VotifierPlus
version: "${project.version}"
description: ${project.description}
author: BenCodez
api-version: 1.13
provides: 
- Votifier
folia-supported: true
commands:
  votifierplus:
    description: main command
